### ISSUE TITLE
Suggested additions: 3blue1brown, Manim library, GeoGebra, Complexity Explorables?

### ISSUE THREAD

**Issue by janeadams** [fredhohman/awesome-mathematical-notation-design#27]
For collections:

- Grant Sanderson's [3blue1brown](https://www.youtube.com/c/3blue1brown) channel
- [Complexity Explorables](https://www.complexity-explorables.org/) by Dirk Brockman*
*(not sure if this counts because it is light on notation but heavy on simulation, but interesting collection nonetheless)*

For tools:
- the [Manim](https://github.com/3b1b/manim) library, created for 3blue1brown and released for mathematical animation
- [GeoGebra](https://www.geogebra.org/m/Jz9AP6m8) in-browser function graphing tool (link goes to select examples)

For examples:
- [Quaternions](https://eater.net/quaternions) interactive video by Grant Sanderson and Ben Eater

**Comment by fredhohman** [comment]
Great suggestions @janeadams! I'll add them soon.
