### ISSUE TITLE
Example from dalek-cryptography/bulletproofs repository

### ISSUE THREAD

**Issue by htadashi** [fredhohman/awesome-mathematical-notation-design#28]
This color-coded diagram greatly eases the understanding of this zero-knowledge cryptography protocol:

https://camo.githubusercontent.com/97e1577fed4ac754d5d6acd28c539e6c4d35d89d6a8a21b1bebd86e56f6fa812/68747470733a2f2f646f632e64616c656b2e72732f6173736574732f62756c6c657470726f6f66732d72616e676570726f6f662e706e67

**Comment by fredhohman** [comment]
Thanks for the suggestion @htadashi!
