### ISSUE TITLE
The Art of Linear Algebra

### ISSUE THREAD

**Issue by cben** [fredhohman/awesome-mathematical-notation-design#29]
https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra/  
This uses carefully consistent color and shapes to highlight multiple viewpoints on the very same matrix multiplication formulas.  
It's intended as notes for a book (which I haven't read) but I guess can fit under "Articles".

**Comment by fredhohman** [comment]
Thanks for the recommendation @cben! I've added the example.
