### ISSUE TITLE
Add example: VAE Explainer

### ISSUE THREAD

**Issue by xnought** [fredhohman/awesome-mathematical-notation-design#30]
Website: https://xnought.github.io/vae-explainer/

Colored equations + colored code + live computational graph

https://github.com/user-attachments/assets/8bcbab49-4057-4124-8dec-501a234b39be

**Comment by fredhohman** [comment]
Great example! Will add soon.

**Comment by fredhohman** [comment]
@xnought added!

**Comment by xnought** [comment]
Thanks Fred!
